# Generated by Django 4.0.1 on 2022-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=10)),
                ('material_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('inserted_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
