# Generated by Django 4.0.1 on 2022-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=10)),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('material_description', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AlterField(
            model_name='scraptable',
            name='inserted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
